### ISSUE TITLE
Give better feedback to users in event details page

### ISSUE THREAD

**Issue by ErkanBasar** [LanguageMachines/LamaEvents#4] opened 2018-03-13 09:55 UTC
## Summary
When a user clicks on an event in the calendar, the tweets relating to that event should be displayed. Right now, nothing displayed under the title "Tweets over dit event".

## Possible Problems
* ~~Data structure might be incorrect. Thus it may not be able to find what to display.~~
* ~~There might be something wrong with the Twitter widgets, e.g. using an old version, a change in the widget URL or problem with API key.~~

## Solution
After having a discussion with @fkunneman, we concluded that this is normal for some of the events, specifically labelled as `Voorspeld`. They simply are not formed from tweets, so there is no tweet to be displayed. However, when there is no tweet, it looks like something is broken in the system. If there is no tweet to be displayed, at least a message that indicates the reason should appear to clear out the confusion. 

## Steps
- [x] Return an informative message to user if there is no tweet to be displayed
- [x] Place the correct informational messages (there are dummy messages for now)
- [x] Make the messages look nice on the front-end (e.g. aligning to center)

**Comment by ghiathghanem** [comment] 2018-03-13 12:33
Yes that's true, but not for all results because i see it works fine with some links, and i got relating tweets, after i clicked on the Eerderde edities. thus what do you think, problem with the data or something else?

**Comment by ErkanBasar** [comment] 2018-03-14 14:05
I have checked it again and see the tweets under _"Eerderde edities"_ for some of the events. Thus it can not be caused by a problem with Twitter widgets or API. Therefore, this is probably caused by the data. 

I have also discussed this with @fkunneman and we concluded that this is normal for some of the events, specifically labelled as `Voorspeld`. They simply are not formed from tweets, so there is no tweet to be displayed. In this case, a message should be displayed for users to clear out any confusions and to save it from looking like broken. So, this task turns out to be about giving sufficient feedback to the users. I'm updating the issue and the initial comment.

**Comment by ghiathghanem** [comment] 2018-03-15 09:05
I saw the same thing. It was a good idea to discuss that with Florian. I agree with you to display a message to the user to let him knows that nothing went wrong.Thanks Erkan.here is another problem: if we select this date, we will get this result: 
 Zaterdag 18 maart 2017
  Vermoedelijke locatie voor dit event:  Geen locatie bekend voor deze gebeurtenis   
 Periodiciteit: ieder jaar op de 3e zaterdag van maart 

 Eerdere edities: 
  
 2014-03-15 - visio   
 2015-03-21 - visio   
 2016-03-19 - visio   
 2017-03-18 - visio   
 2017-03-18 - visio, bethesda  But when we click on the last one (visio, bethesda) we get page with this message(
DoesNotExist at /58ce553e385ee419d84a7545/eventDetail
) with coding page.
 

    On Wednesday, March 14, 2018, 3:05:47 PM GMT+1, M. Erkan Başar <notifications@github.com> wrote:  
 
 
I have checked it again and see the tweets under "Eerderde edities" for some of the events. Thus it can not be caused by a problem with Twitter widgets or API. Therefore, this is probably caused by the data.

I have also discussed this with @fkunneman and we concluded that this is normal for some of the events, specifically labelled as Voorspeld. They simply are not formed from tweets, so there is no tweet to be displayed. In this case, a message should be displayed for users to clear out any confusions and to save it from looking like broken. So, this task turns out to be about giving sufficient feedback to the users. I'm updating the issue and the initial comment.

**Comment by fkunneman** [comment] 2018-04-06 14:18
Suggested text for cases in which there are no tweets due to the 'voorspeld' module:

"Deze gebeurtenis is niet gebaseerd op de inhoud van tweets, maar wordt verwacht op basis van eerdere edities die periodiek plaatsvinden. Er zijn nog geen tweets geplaatst die naar deze gebeurtenis verwijzen en hier gepresenteerd kunnen worden."  

Suggested text for cases in which all tweets have been removed by the users:

"Voor deze gebeurtenis zijn geen tweets beschikbaar. Een mogelijke verklaring is dat de tweets inmiddels zijn verwijderd door de gebruikers, of dat de gebruikers hun account hebben stopgezet."

**Comment by ghiathghanem** [comment] 2018-04-09 11:30
I did the three steps and run the code locally and now it looks better after the editing. So I think now we can close this issue.

**Closed** 2018-04-11 08:32 UTC
Labels: enhancement
